// Integration test for Mp3File against a real MP3 file (path passed as
// argv[1], generated by the test harness via ffmpeg — no bundled binary
// fixtures in the repo). Verifies format metadata and that decoded output
// is non-empty and not silence. Exact sample equality isn't meaningful for
// lossy MP3 (unlike WavFile's exact-match tests), so this checks structural
// correctness instead.

#include <cmath>
#include <iostream>

#include "Mp3File.h"

using dj::core::audio::Mp3File;

int main(int argc, char** argv) {
    if (argc < 2) {
        std::cerr << "usage: mp3file_test <path-to-mp3>\n";
        return 1;
    }

    int failures = 0;
    auto check = [&](bool cond, const std::string& msg) {
        if (!cond) {
            std::cerr << "FAIL: " << msg << "\n";
            ++failures;
        }
    };

    Mp3File mp3 = Mp3File::loadFromFile(argv[1]);

    check(mp3.sampleRate() == 44100, "decoded sample rate matches source (44100 Hz)");
    check(mp3.channels() == 1, "decoded channel count matches source (mono)");
    check(mp3.frameCount() > 0, "decoded frame count is non-zero");

    bool foundNonSilence = false;
    for (float s : mp3.samples()) {
        if (std::fabs(s) > 0.01f) {
            foundNonSilence = true;
            break;
        }
    }
    check(foundNonSilence, "decoded output is not silence");

    if (failures == 0) {
        std::cout << "mp3file_test: all checks passed\n";
        return 0;
    }
    std::cerr << "mp3file_test: " << failures << " check(s) failed\n";
    return 1;
}
